import type { Celebrity } from '../engine/types.ts';
import { buildSchedule, type PuzzleSchedule } from '../engine/puzzle.ts';
import rawCelebrities from './celebrities.json';
import launch from './launch.json';

/**
 * The dataset is generated by `npm run dataset:build`. It is bundled rather than
 * fetched so the game works offline after first load; see README "Security" for why
 * that is an acceptable trade-off for a daily guessing game.
 */
export const celebrities = rawCelebrities as unknown as Celebrity[];

/** The game's first puzzle day, and the floor of the playable archive. */
export const launchDate: string = launch.date;

/**
 * The date -> star mapping, rebuilt in the browser each session.
 *
 * Deliberately not a shipped file: the repository is public, and a committed
 * schedule would let anyone read off future answers without even running the game.
 * See `buildSchedule` for what this does and does not protect.
 */
export function scheduleThrough(today: string): PuzzleSchedule {
  return buildSchedule(celebrities, launchDate, today);
}

export const playableCelebrities = celebrities.filter((celebrity) => celebrity.playable);

/** Minimum playable roster before the game is worth shipping (PRD §52). */
export const MIN_PLAYABLE = 50;

export function datasetError(): string | undefined {
  if (celebrities.length === 0) {
    return 'The celebrity dataset is empty. Run `npm run dataset:build` to generate it.';
  }
  if (playableCelebrities.length < MIN_PLAYABLE) {
    return `Only ${playableCelebrities.length} playable celebrities are available; at least ${MIN_PLAYABLE} are needed. Re-run \`npm run dataset:build\`.`;
  }
  return undefined;
}
